CREATE TABLE "responsaveis" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "senha" string NOT NULL,
  "nome" string NOT NULL,
  "email" string NOT NULL,
  "dt_nascimento" timestamp NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "criancas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_pai" integer NOT NULL,
  "nome" string NOT NULL,
  "idade" integer NOT NULL,
  "altura" integer NOT NULL,
  "peso" integer NOT NULL,
  "genero" char NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "desenvolvimento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_crianca" integer NOT NULL,
  "descricao" string NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "crescimento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_crianca" integer NOT NULL,
  "peso" integer NOT NULL,
  "altura" integer NOT NULL,
  "circ_cabeca" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "sono" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_crianca" integer NOT NULL,
  "acordar" timestamp NOT NULL,
  "dormir" timestamp NOT NULL
);

CREATE TABLE "vacinas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_pai" integer NOT NULL,
  "nome" string NOT NULL,
  "quant_doses" int
);

CREATE TABLE "aplicacoes_vacinas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_vacina" integer NOT NULL,
  "id_crianca" integer NOT NULL,
  "data" timestamp NOT NULL,
  "dose" integer NOT NULL
);

CREATE TABLE "consultas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_crianca" integer NOT NULL,
  "data" timestamp NOT NULL,
  "medico" string NOT NULL,
  "especialidade" string
);

ALTER TABLE "criancas" ADD FOREIGN KEY ("id_pai") REFERENCES "responsaveis" ("id");

ALTER TABLE "desenvolvimento" ADD FOREIGN KEY ("id_crianca") REFERENCES "criancas" ("id");

ALTER TABLE "crescimento" ADD FOREIGN KEY ("id_crianca") REFERENCES "criancas" ("id");

ALTER TABLE "sono" ADD FOREIGN KEY ("id_crianca") REFERENCES "criancas" ("id");

ALTER TABLE "vacinas" ADD FOREIGN KEY ("id_pai") REFERENCES "responsaveis" ("id");

ALTER TABLE "aplicacoes_vacinas" ADD FOREIGN KEY ("id_vacina") REFERENCES "vacinas" ("id");

ALTER TABLE "aplicacoes_vacinas" ADD FOREIGN KEY ("id_crianca") REFERENCES "criancas" ("id");

ALTER TABLE "consultas" ADD FOREIGN KEY ("id_crianca") REFERENCES "criancas" ("id");
